# .github/workflows/run-n8n.yml
name: Run n8n Session

on:
  workflow_dispatch:

jobs:
  n8n_session:
    runs-on: ubuntu-latest
    
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          # Use Node.js v20 to match n8n's requirements
          node-version: '20'

      - name: Install n8n
        run: npm install -g n8n

      - name: Install and Configure ngrok
        run: |
          wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz -O ngrok.tgz
          sudo tar -xvzf ngrok.tgz -C /usr/local/bin
          rm ngrok.tgz
          ngrok config add-authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
          
      - name: Run n8n and Start ngrok Tunnel
        run: |
          echo "Starting n8n server in the background..."
          n8n &> n8n.log &
          
          echo "Starting ngrok tunnel..."
          ngrok http 5678 &> /dev/null &
          
          sleep 10
          
          sudo apt-get install -y jq
          N8N_URL=$(curl --silent http://127.0.0.1:4040/api/tunnels | jq -r '.tunnels[0].public_url')
          
          if [ -z "$N8N_URL" ]; then
            echo "::error::Could not retrieve ngrok tunnel URL."
            exit 1
          fi
          
          echo "✅ n8n instance is running and accessible!"
          echo "--------------------------------------------------------"
          echo "Access your n8n instance at this URL:"
          echo $N8N_URL
          echo "--------------------------------------------------------"
          
          while true; do sleep 1000; done
