# .github/workflows/run-n8n.yml
name: Run n8n Session (Docker)

on:
  workflow_dispatch:

jobs:
  n8n_session:
    runs-on: ubuntu-latest
    
    steps:
      - name: Free Up Disk Space
        run: |
          echo "Initial disk space:"
          df -h
          # Remove large pre-installed tools we don't need
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf /usr/local/share/boost
          sudo rm -rf $AGENT_TOOLSDIRECTORY
          echo "Disk space after cleanup:"
          df -h

      - name: Install and Configure ngrok
        run: |
          wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz -O ngrok.tgz
          sudo tar -xvzf ngrok.tgz -C /usr/local/bin
          rm ngrok.tgz
          ngrok config add-authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
          
      - name: Run n8n via Docker and Start ngrok Tunnel
        run: |
          # Start the official n8n Docker container in the background
          echo "Starting n8n Docker container..."
          docker run -d --name n8n -p 5678:5678 n8nio/n8n
          
          # --- ROBUST WAITING LOGIC ---
          echo "Waiting for n8n to become available on port 5678..."
          max_wait=120 # Wait up to 2 minutes for the container to start
          count=0
          while ! curl --silent --fail http://localhost:5678 &>/dev/null; do
              if [ $count -ge $max_wait ]; then
                  echo "::error::n8n container failed to start within $max_wait seconds."
                  echo "--- Docker container logs ---"
                  docker logs n8n
                  exit 1
              fi
              printf "."
              sleep 1
              ((count++))
          done
          echo ""
          echo "✅ n8n container is up and running!"
          
          # Start
